export const 
RTI_FORM_STEP = 'RTI_FORM_STEP',
AUTH_SUCCESS = 'AUTH_SUCCESS', 
AUTH_FAILURE = 'AUTH_FAILURE', 
AUTH_LOGOUT = 'AUTH_LOGOUT',
AUTH_REQUEST = 'AUTH_REQUEST',
AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';